//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CsprojUWP
{
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/developer/msbuild/2003", IsNullable = false)]
    public partial class Project
    {

        private ProjectImport[] importField;

        private ProjectPropertyGroup[] propertyGroupField;

        private ProjectItemGroup[] itemGroupField;

        private string toolsVersionField;

        private string defaultTargetsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Import")]
        public ProjectImport[] Import
        {
            get
            {
                return this.importField;
            }
            set
            {
                this.importField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyGroup")]
        public ProjectPropertyGroup[] PropertyGroup
        {
            get
            {
                return this.propertyGroupField;
            }
            set
            {
                this.propertyGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemGroup")]
        public ProjectItemGroup[] ItemGroup
        {
            get
            {
                return this.itemGroupField;
            }
            set
            {
                this.itemGroupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ToolsVersion
        {
            get
            {
                return this.toolsVersionField;
            }
            set
            {
                this.toolsVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultTargets
        {
            get
            {
                return this.defaultTargetsField;
            }
            set
            {
                this.defaultTargetsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectImport
    {

        private string projectField;

        private string conditionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectPropertyGroup
    {

        private string debugSymbolsField;

        private string signAssemblyField;

        private string visualStudioVersionField;

        private string useDotNetNativeSharedAssemblyFrameworkPackageField;

        private string disableXbfLineInfoField;

        private string outputPathField;

        private string defineConstantsField;

        private string optimizeField;

        private string noWarnField;

        private string noStdLibField;

        private string debugTypeField;

        private string platformTargetField;

        private string useVSHostingProcessField;

        private string errorReportField;

        private string codeAnalysisRuleSetField;

        private string prefer32BitField;

        private string useDotNetNativeToolchainField;

        private string projectGuidField;

        private string outputTypeField;

        private string appDesignerFolderField;

        private string rootNamespaceField;

        private string assemblyNameField;

        private string defaultLanguageField;

        private string targetPlatformIdentifierField;

        private string targetPlatformVersionField;

        private string targetPlatformMinVersionField;

        private string minimumVisualStudioVersionField;

        private string enableDotNetNativeCompatibleProfileField;

        private string fileAlignmentField;

        private string projectTypeGuidsField;

        private string packageCertificateKeyFileField;

        private string appxAutoIncrementPackageRevisionField;

        private string appxBundleField;

        private string appxBundlePlatformsField;

        private string appxSymbolPackageEnabledField;

        private string packageCertificateThumbprintField;

        private string hockeyAppResourceIdField;

        private string runtimeIdentifiersField;

        private string generateAppInstallerFileField;

        private string appInstallerUpdateFrequencyField;

        private string appInstallerCheckForUpdateFrequencyField;

        private string preBuildEventField;

        private ProjectPropertyGroupConfiguration[] configurationField;

        private ProjectPropertyGroupPlatform[] platformField;

        private string conditionField;

        /// <remarks/>
        public string DebugSymbols
        {
            get
            {
                return this.debugSymbolsField;
            }
            set
            {
                this.debugSymbolsField = value;
            }
        }

        /// <remarks/>
        public string SignAssembly
        {
            get
            {
                return this.signAssemblyField;
            }
            set
            {
                this.signAssemblyField = value;
            }
        }

        /// <remarks/>
        public string VisualStudioVersion
        {
            get
            {
                return this.visualStudioVersionField;
            }
            set
            {
                this.visualStudioVersionField = value;
            }
        }

        /// <remarks/>
        public string UseDotNetNativeSharedAssemblyFrameworkPackage
        {
            get
            {
                return this.useDotNetNativeSharedAssemblyFrameworkPackageField;
            }
            set
            {
                this.useDotNetNativeSharedAssemblyFrameworkPackageField = value;
            }
        }

        /// <remarks/>
        public string DisableXbfLineInfo
        {
            get
            {
                return this.disableXbfLineInfoField;
            }
            set
            {
                this.disableXbfLineInfoField = value;
            }
        }

        /// <remarks/>
        public string OutputPath
        {
            get
            {
                return this.outputPathField;
            }
            set
            {
                this.outputPathField = value;
            }
        }

        /// <remarks/>
        public string DefineConstants
        {
            get
            {
                return this.defineConstantsField;
            }
            set
            {
                this.defineConstantsField = value;
            }
        }

        /// <remarks/>
        public string Optimize
        {
            get
            {
                return this.optimizeField;
            }
            set
            {
                this.optimizeField = value;
            }
        }

        /// <remarks/>
        public string NoWarn
        {
            get
            {
                return this.noWarnField;
            }
            set
            {
                this.noWarnField = value;
            }
        }

        /// <remarks/>
        public string NoStdLib
        {
            get
            {
                return this.noStdLibField;
            }
            set
            {
                this.noStdLibField = value;
            }
        }

        /// <remarks/>
        public string DebugType
        {
            get
            {
                return this.debugTypeField;
            }
            set
            {
                this.debugTypeField = value;
            }
        }

        /// <remarks/>
        public string PlatformTarget
        {
            get
            {
                return this.platformTargetField;
            }
            set
            {
                this.platformTargetField = value;
            }
        }

        /// <remarks/>
        public string UseVSHostingProcess
        {
            get
            {
                return this.useVSHostingProcessField;
            }
            set
            {
                this.useVSHostingProcessField = value;
            }
        }

        /// <remarks/>
        public string ErrorReport
        {
            get
            {
                return this.errorReportField;
            }
            set
            {
                this.errorReportField = value;
            }
        }

        /// <remarks/>
        public string CodeAnalysisRuleSet
        {
            get
            {
                return this.codeAnalysisRuleSetField;
            }
            set
            {
                this.codeAnalysisRuleSetField = value;
            }
        }

        /// <remarks/>
        public string Prefer32Bit
        {
            get
            {
                return this.prefer32BitField;
            }
            set
            {
                this.prefer32BitField = value;
            }
        }

        /// <remarks/>
        public string UseDotNetNativeToolchain
        {
            get
            {
                return this.useDotNetNativeToolchainField;
            }
            set
            {
                this.useDotNetNativeToolchainField = value;
            }
        }

        /// <remarks/>
        public string ProjectGuid
        {
            get
            {
                return this.projectGuidField;
            }
            set
            {
                this.projectGuidField = value;
            }
        }

        /// <remarks/>
        public string OutputType
        {
            get
            {
                return this.outputTypeField;
            }
            set
            {
                this.outputTypeField = value;
            }
        }

        /// <remarks/>
        public string AppDesignerFolder
        {
            get
            {
                return this.appDesignerFolderField;
            }
            set
            {
                this.appDesignerFolderField = value;
            }
        }

        /// <remarks/>
        public string RootNamespace
        {
            get
            {
                return this.rootNamespaceField;
            }
            set
            {
                this.rootNamespaceField = value;
            }
        }

        /// <remarks/>
        public string AssemblyName
        {
            get
            {
                return this.assemblyNameField;
            }
            set
            {
                this.assemblyNameField = value;
            }
        }

        /// <remarks/>
        public string DefaultLanguage
        {
            get
            {
                return this.defaultLanguageField;
            }
            set
            {
                this.defaultLanguageField = value;
            }
        }

        /// <remarks/>
        public string TargetPlatformIdentifier
        {
            get
            {
                return this.targetPlatformIdentifierField;
            }
            set
            {
                this.targetPlatformIdentifierField = value;
            }
        }

        /// <remarks/>
        public string TargetPlatformVersion
        {
            get
            {
                return this.targetPlatformVersionField;
            }
            set
            {
                this.targetPlatformVersionField = value;
            }
        }

        /// <remarks/>
        public string TargetPlatformMinVersion
        {
            get
            {
                return this.targetPlatformMinVersionField;
            }
            set
            {
                this.targetPlatformMinVersionField = value;
            }
        }

        /// <remarks/>
        public string MinimumVisualStudioVersion
        {
            get
            {
                return this.minimumVisualStudioVersionField;
            }
            set
            {
                this.minimumVisualStudioVersionField = value;
            }
        }

        /// <remarks/>
        public string EnableDotNetNativeCompatibleProfile
        {
            get
            {
                return this.enableDotNetNativeCompatibleProfileField;
            }
            set
            {
                this.enableDotNetNativeCompatibleProfileField = value;
            }
        }

        /// <remarks/>
        public string FileAlignment
        {
            get
            {
                return this.fileAlignmentField;
            }
            set
            {
                this.fileAlignmentField = value;
            }
        }

        /// <remarks/>
        public string ProjectTypeGuids
        {
            get
            {
                return this.projectTypeGuidsField;
            }
            set
            {
                this.projectTypeGuidsField = value;
            }
        }

        /// <remarks/>
        public string PackageCertificateKeyFile
        {
            get
            {
                return this.packageCertificateKeyFileField;
            }
            set
            {
                this.packageCertificateKeyFileField = value;
            }
        }

        /// <remarks/>
        public string AppxAutoIncrementPackageRevision
        {
            get
            {
                return this.appxAutoIncrementPackageRevisionField;
            }
            set
            {
                this.appxAutoIncrementPackageRevisionField = value;
            }
        }

        /// <remarks/>
        public string AppxBundle
        {
            get
            {
                return this.appxBundleField;
            }
            set
            {
                this.appxBundleField = value;
            }
        }

        /// <remarks/>
        public string AppxBundlePlatforms
        {
            get
            {
                return this.appxBundlePlatformsField;
            }
            set
            {
                this.appxBundlePlatformsField = value;
            }
        }

        /// <remarks/>
        public string AppxSymbolPackageEnabled
        {
            get
            {
                return this.appxSymbolPackageEnabledField;
            }
            set
            {
                this.appxSymbolPackageEnabledField = value;
            }
        }

        /// <remarks/>
        public string PackageCertificateThumbprint
        {
            get
            {
                return this.packageCertificateThumbprintField;
            }
            set
            {
                this.packageCertificateThumbprintField = value;
            }
        }

        /// <remarks/>
        public string HockeyAppResourceId
        {
            get
            {
                return this.hockeyAppResourceIdField;
            }
            set
            {
                this.hockeyAppResourceIdField = value;
            }
        }

        /// <remarks/>
        public string RuntimeIdentifiers
        {
            get
            {
                return this.runtimeIdentifiersField;
            }
            set
            {
                this.runtimeIdentifiersField = value;
            }
        }

        /// <remarks/>
        public string GenerateAppInstallerFile
        {
            get
            {
                return this.generateAppInstallerFileField;
            }
            set
            {
                this.generateAppInstallerFileField = value;
            }
        }

        /// <remarks/>
        public string AppInstallerUpdateFrequency
        {
            get
            {
                return this.appInstallerUpdateFrequencyField;
            }
            set
            {
                this.appInstallerUpdateFrequencyField = value;
            }
        }

        /// <remarks/>
        public string AppInstallerCheckForUpdateFrequency
        {
            get
            {
                return this.appInstallerCheckForUpdateFrequencyField;
            }
            set
            {
                this.appInstallerCheckForUpdateFrequencyField = value;
            }
        }

        /// <remarks/>
        public string PreBuildEvent
        {
            get
            {
                return this.preBuildEventField;
            }
            set
            {
                this.preBuildEventField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Configuration", IsNullable = true)]
        public ProjectPropertyGroupConfiguration[] Configuration
        {
            get
            {
                return this.configurationField;
            }
            set
            {
                this.configurationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Platform", IsNullable = true)]
        public ProjectPropertyGroupPlatform[] Platform
        {
            get
            {
                return this.platformField;
            }
            set
            {
                this.platformField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectPropertyGroupConfiguration
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectPropertyGroupPlatform
    {

        private string conditionField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroup
    {

        private ProjectItemGroupContent[] contentField;

        private ProjectItemGroupNone[] noneField;

        private ProjectItemGroupCompile[] compileField;

        private ProjectItemGroupAppxManifest[] appxManifestField;

        private ProjectItemGroupApplicationDefinition[] applicationDefinitionField;

        private ProjectItemGroupPage[] pageField;

        private ProjectItemGroupFolder[] folderField;

        private ProjectItemGroupSDKReference[] sDKReferenceField;

        private ProjectItemGroupProjectReference[] projectReferenceField;

        private ProjectItemGroupPackageReference[] packageReferenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Content")]
        public ProjectItemGroupContent[] Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("None")]
        public ProjectItemGroupNone[] None
        {
            get
            {
                return this.noneField;
            }
            set
            {
                this.noneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Compile")]
        public ProjectItemGroupCompile[] Compile
        {
            get
            {
                return this.compileField;
            }
            set
            {
                this.compileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AppxManifest")]
        public ProjectItemGroupAppxManifest[] AppxManifest
        {
            get
            {
                return this.appxManifestField;
            }
            set
            {
                this.appxManifestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ApplicationDefinition")]
        public ProjectItemGroupApplicationDefinition[] ApplicationDefinition
        {
            get
            {
                return this.applicationDefinitionField;
            }
            set
            {
                this.applicationDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Page")]
        public ProjectItemGroupPage[] Page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder")]
        public ProjectItemGroupFolder[] Folder
        {
            get
            {
                return this.folderField;
            }
            set
            {
                this.folderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SDKReference")]
        public ProjectItemGroupSDKReference[] SDKReference
        {
            get
            {
                return this.sDKReferenceField;
            }
            set
            {
                this.sDKReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProjectReference")]
        public ProjectItemGroupProjectReference[] ProjectReference
        {
            get
            {
                return this.projectReferenceField;
            }
            set
            {
                this.projectReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PackageReference")]
        public ProjectItemGroupPackageReference[] PackageReference
        {
            get
            {
                return this.packageReferenceField;
            }
            set
            {
                this.packageReferenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupContent
    {

        private string copyToOutputDirectoryField;

        private string includeField;

        /// <remarks/>
        public string CopyToOutputDirectory
        {
            get
            {
                return this.copyToOutputDirectoryField;
            }
            set
            {
                this.copyToOutputDirectoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupNone
    {

        private string subTypeField;

        private string includeField;

        /// <remarks/>
        public string SubType
        {
            get
            {
                return this.subTypeField;
            }
            set
            {
                this.subTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupCompile
    {

        private string dependentUponField;

        private string includeField;

        /// <remarks/>
        public string DependentUpon
        {
            get
            {
                return this.dependentUponField;
            }
            set
            {
                this.dependentUponField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupAppxManifest
    {

        private string subTypeField;

        private string includeField;

        /// <remarks/>
        public string SubType
        {
            get
            {
                return this.subTypeField;
            }
            set
            {
                this.subTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupApplicationDefinition
    {

        private string generatorField;

        private string subTypeField;

        private string includeField;

        /// <remarks/>
        public string Generator
        {
            get
            {
                return this.generatorField;
            }
            set
            {
                this.generatorField = value;
            }
        }

        /// <remarks/>
        public string SubType
        {
            get
            {
                return this.subTypeField;
            }
            set
            {
                this.subTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupPage
    {

        private string subTypeField;

        private string generatorField;

        private string copyToOutputDirectoryField;

        private string includeField;

        /// <remarks/>
        public string SubType
        {
            get
            {
                return this.subTypeField;
            }
            set
            {
                this.subTypeField = value;
            }
        }

        /// <remarks/>
        public string Generator
        {
            get
            {
                return this.generatorField;
            }
            set
            {
                this.generatorField = value;
            }
        }

        /// <remarks/>
        public string CopyToOutputDirectory
        {
            get
            {
                return this.copyToOutputDirectoryField;
            }
            set
            {
                this.copyToOutputDirectoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupFolder
    {

        private string includeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupSDKReference
    {

        private string nameField;

        private string includeField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupProjectReference
    {

        private string projectField;

        private string nameField;

        private string includeField;

        /// <remarks/>
        public string Project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupPackageReference
    {

        private string versionField;

        private string includeField;

        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/developer/msbuild/2003", IsNullable = false)]
    public partial class NewDataSet
    {

        private Project[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Project")]
        public Project[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}